trigger:
- master

variables:
- group: test
- name: namespace1
  value: 'yourNamespace1'
- name: capability1
  value: 'yourCapability1'
- name: namespace2
  value: 'yourNamespace2'
- name: capability2
  value: 'yourCapability2'

stages:
- stage: DisplayVariables
  displayName: 'Display Environment Variables'
  jobs:
  - job: Display
    displayName: 'Display'
    steps:
    - script: |
        env
        echo $(ENV_$(namespace1.toUpperCase())_$(capability1.toUpperCase()))
        echo $(ENV_$(namespace2.toUpperCase())_$(capability2.toUpperCase()))
      displayName: 'Display environment variables'
