trigger:
- master

variables:
- group: test
- name: namespace1
  value: 'yourNamespace1'
- name: capability1
  value: 'yourCapability1'
- name: namespace2
  value: 'yourNamespace2'
- name: capability2
  value: 'yourCapability2'

stages:
- stage: DisplayVariables
  displayName: 'Display Environment Variables'
  jobs:
  - job: Display
    displayName: 'Display'
    steps:
    - script: |
        env
        echo "ENV_$(namespace1)_$(capability1): $ENV_$(tr $(namespace1))_$(tr $(capability1))"
        echo "ENV_$(namespace2)_$(capability2): $ENV_$(namespace2)_$(capability2)"
      displayName: 'Display environment variables'
