trigger:
- master

variables:
- group: test
- name: namespace1
  value: 'yourNamespace1'
- name: capability1
  value: 'yourCapability1'
- name: namespace2
  value: 'yourNamespace2'
- name: capability2
  value: 'yourCapability2'

stages:
- stage: DisplayVariables
  displayName: 'Display Environment Variables'
  jobs:
  - job: Display
    displayName: 'Display'
    steps:
    - script: |
        env
        echo value for namespace1 is $(namespace1)
        echo ENV_$(echo "$(namespace1)" | tr '[:lower:]' '[:upper:]')_$(echo "$(capability1)" | tr '[:lower:]' '[:upper:]')
        echo $(ENV_$(echo "$(namespace1)" | tr '[:lower:]' '[:upper:]')_$(echo "$(capability1)" | tr '[:lower:]' '[:upper:]'))
      displayName: 'Display environment variables'
