parameters:
- name: library-name

stages:
- stage: Stage1
  jobs:
  - job: Stage1Job
    variables:
    - group: ${{ parameters['library-name'] }}
    steps:
    - script: echo stage1 $(cred.user)
- stage: Stage2
  jobs:
  - job: Stage2Job
    steps:
    - script: echo stage2
